name: ENV with Parallel Jobs
 
on:
  push:
    branches:
      - main
 
env:
  COMPANY: OpenAI
 
jobs:
  job-one:
    runs-on: ubuntu-latest
    env:
      ROLE: Backend
 
    steps:
      - name: Job One ENV
        run: |
          echo "Company is $COMPANY"
          echo "Role is $ROLE"
 
  job-two:
    runs-on: ubuntu-latest
    env:
      ROLE: DevOps
 
    steps:
      - name: Job Two ENV
        run: |
          echo "Company is $COMPANY"
          echo "Role is $ROLE"
