name: Secret Demo
 
on:
  push:
    branches:
      - main
 
jobs:
  secret-job:
    runs-on: ubuntu-latest
 
    steps:
      - name: Use secret safely
        env:
          MSG: ${{ secrets.MY_SECRET }}
        run: echo "My secret value is $MSG"
